name: deploy
run-name: run tests

on:
  push:
    branches:
      - develop
defaults:
  run:
    shell: bash
jobs:
  select_environment:
    name: Select Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref_name }}"
          case ${{ github.ref_name }} in
            main)
              name=Main
              ;;
            develop)
              name=Develop
              ;;
          esac
          echo "selected environment: $name"
          echo "env_name=$name" >> $GITHUB_OUTPUT
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
  build-and-push:
    name: Build and push
    needs: select_environment
    runs-on: self-hosted
    environment: ${{ needs.select_environment.outputs.env_name }}
    steps:
      - run: ls #cd chatbot && git pull origin develop

        

